# Generated by Django 6.0.6 on 2026-06-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Costo')),
                ('stock_actual', models.IntegerField(verbose_name='Stock Disponible')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado del Producto')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubicaciones.ubicacion', verbose_name='Ubicación en Bodega')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
