# Generated by Django 6.0.6 on 2026-06-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ubicaciones.ubicacion', verbose_name='Ubicación en Bodega'),
            preserve_default=False,
        ),
    ]
