# Generated by Django 6.0.6 on 2026-06-30 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.IntegerField(verbose_name='Cantidad a Retirar')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Salida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto Despachado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario/Responsable')),
            ],
            options={
                'verbose_name': 'Orden de Salida',
                'verbose_name_plural': 'Órdenes de Salida',
            },
        ),
    ]
