# Generated by Django 6.0.6 on 2026-06-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fabricacion', models.DateField(verbose_name='Fecha de Fabricación')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('cantidad_inicial', models.IntegerField(verbose_name='Cantidad Inicial del Lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto Asociado')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
