# Generated by Django 6.0.6 on 2026-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa / Razón Social')),
                ('ruc_proveedor', models.CharField(max_length=13, unique=True, verbose_name='RUC del Proveedor')),
                ('telefono_contacto', models.CharField(max_length=15, verbose_name='Teléfono de Contacto')),
                ('direccion_matriz', models.TextField(verbose_name='Dirección Matriz')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
