# Generated by Django 6.0.6 on 2026-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100, verbose_name='Nombre del Área / Zona')),
                ('capacidad_maxima', models.IntegerField(verbose_name='Capacidad Máxima (Unidades)')),
                ('seccion_fila', models.CharField(max_length=100, verbose_name='Sección y Fila (Coordenadas)')),
                ('estado_espacio', models.CharField(choices=[('disponible', 'Disponible'), ('lleno', 'Lleno'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado del Espacio')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
    ]
